name: AID_Multilabel
folder_name: aid
num_classes: 17

hierarchy:
  1. Artificial surfaces:
    1.1 Urban fabric:
      buildings: {}
      mobile-home: {}
    1.2 Industrial, commercial, and transport units:
      1.2.1 Industrial or commercial units:
        tanks: {}
      1.2.2 Road and rail networks and associated land:
        cars: {}
        pavement: {}
      1.2.3 Port areas:
        dock: {}
        ship: {}
      1.2.4 Airports:
        airplane: {}
    1.3 Mine, dump, and construction sites:
      bare-soil: {}
    1.4 Artificial, non-agricultural vegetated areas:
      # CORINE often places sports/leisure here
      1.4.2 Sport and leisure facilities:
        court: {}

  2. Agricultural areas:
    2.1 Arable land:
      field: {}

  3. Forest and semi-natural areas:
    3.1 Forests:
      trees: {}
    3.2 Scrub and/or herbaceous vegetation associations:
      chaparral: {}
      grass: {}

  5. Water bodies:
    5.1 Inland waters:
      water: {}
    5.2 Marine waters:
      sand: {}
      sea: {}

leaf_labels:
  - airplane
  - bare-soil
  - buildings
  - cars
  - chaparral
  - court
  - dock
  - field
  - grass
  - mobile-home
  - pavement
  - sand
  - sea
  - ship
  - tanks
  - trees
  - water
