name: Oxford-IIIT Pets
folder_name: oxfordpets
num_classes: 37
hierarchy:
    cat:
      Abyssinian: {}
      Bengal: {}
      Birman: {}
      Bombay: {}
      British_Shorthair: {}
      Egyptian_Mau: {}
      Maine_Coon: {}
      Persian: {}
      Ragdoll: {}
      Russian_Blue: {}
      Siamese: {}
      Sphynx: {}
    dog:
      american_bulldog: {}
      american_pit_bull_terrier: {}
      basset_hound: {}
      beagle: {}
      boxer: {}
      chihuahua: {}
      english_cocker_spaniel: {}
      english_setter: {}
      german_shorthaired: {}
      great_pyrenees: {}
      havanese: {}
      japanese_chin: {}
      keeshond: {}
      leonberger: {}
      miniature_pinscher: {}
      newfoundland: {}
      pomeranian: {}
      pug: {}
      saint_bernard: {}
      samoyed: {}
      scottish_terrier: {}
      shiba_inu: {}
      staffordshire_bull_terrier: {}
      wheaten_terrier: {}
      yorkshire_terrier: {}
leaf_labels:
  - Abyssinian
  - Bengal
  - Birman
  - Bombay
  - British_Shorthair
  - Egyptian_Mau
  - Maine_Coon
  - Persian
  - Ragdoll
  - Russian_Blue
  - Siamese
  - Sphynx
  - american_bulldog
  - american_pit_bull_terrier
  - basset_hound
  - beagle
  - boxer
  - chihuahua
  - english_cocker_spaniel
  - english_setter
  - german_shorthaired
  - great_pyrenees
  - havanese
  - japanese_chin
  - keeshond
  - leonberger
  - miniature_pinscher
  - newfoundland
  - pomeranian
  - pug
  - saint_bernard
  - samoyed
  - scottish_terrier
  - shiba_inu
  - staffordshire_bull_terrier
  - wheaten_terrier
  - yorkshire_terrier